apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prac9p-mongo-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: prac9p-mongo-pv
  storageClassName: "prac9p-storage"