apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-deployment
  labels:
    app: myapp
    tier: calculator-backend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: calculator-backend
  template:
    metadata:
      labels:
        tier: calculator-backend
    spec:
      containers:
      - name: simple-calculator-service
        image: tut888/sit737-prac6p-service
        ports:
        - containerPort: 3040