apiVersion: apps/v1
kind: Deployment
metadata:
  name: prac6c-deployment
  labels:
    app: myapp-6c
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: myapp-6c
  template:
    metadata:
      labels:
        app: myapp-6c
    spec:
      containers:
      - name: node-cal-service
        image: prac6-service:plus
        imagePullPolicy: Never
        ports:
        - containerPort: 3040