apiVersion: v1
kind: PersistentVolume
metadata:
  name: prac9p-mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  local:
    path: /run/desktop/mnt/host/c/Users/tatta/Desktop/MongoMappedFolder
  storageClassName: "prac9p-storage"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop