apiVersion: v1
kind: Pod
metadata:
  name: prac6p-pod
  labels:
    run: prac6p-pod
spec:
  containers:
  - image: tut888/sit737-prac6p-service
    name: node-cal-service
    ports:
    - containerPort: 3040
  dnsPolicy: ClusterFirst
  restartPolicy: Always